# app/config.yaml
seed: 42

dataset:
  use_data: "woundsegmentation"  # or "dummy"
  root_dir: "/root/autodl-tmp/dataset/wound_segmentation_classification_processed"
  split: "train"

train:
  max_len: 1536
  img_size: [512, 512]
  img_dir: "./data_images"
  batch_size: 2
  epochs: 3
  grad_acc_steps: 1
  early_stop_patience: 3
  clip_grad_norm: 1.0
  output_dir: "runs"
  run_name: "sam4mllm"
  use_amp: true
  log_interval: 2

optimizer:
  lr: 0.0001
  scheduler_type: "linear"  # or "cosine"
  warmup_steps: 1000

model:
  sam: "/root/autodl-tmp/hfweights/sam-vit-base"        # Path or HF repo for your SAM checkpoint if needed
  qwen: "/root/autodl-tmp/hfweights/qwen2vl2b"  # Path or HF repo for Qwen2-VL model
