seed: 42

dataset:
  use_data: "woundsegmentation"  # or "dummy"
  root_dir: "/home/dbcloud/桌面/wound_segmentation_classification_processed"
  split: "train"

train:
  max_len: 1536
  img_size: [512, 512]
  img_dir: "./data_images"
  batch_size: 2
  epochs: 3
  grad_acc_steps: 1
  early_stop_patience: 3
  clip_grad_norm: 1.0
  output_dir: "runs"
  run_name: "sam4mllm_demo"
  use_amp: true
  log_interval: 2

optimizer:
  lr: 1e-4
  scheduler_type: "linear"  # or "cosine"
  warmup_steps: 1000

model:
  sam: "/home/dbcloud/PycharmProjects/mllm4sam/sam-vit-base"          # Path or HF repo for your SAM checkpoint if needed
  qwen: "/home/dbcloud/PycharmProjects/mllm4sam/Qwen2-VL-2B-Instruct"    # Path or HF repo for Qwen model
